server:
  port: 8787

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vankely?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: tiger
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: 12345
    timeout: 15000
    expire: 600
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
      timeout: 15000
      expire: 600

mybatis:
    mapper-locations: classpath:mybatis/*.xml
    type-aliases-package: com.ywh.demo.model


rocketmq:
  producer-group: vanke-user-producer
  provider: rocketmq
  redis-repeat-key: test:mq:message:%s:%s
  rocketmq:
    #namesrv-addr: 192.168.234.250:9876;192.168.235.19:9876
    namesrv-addr: 192.168.235.22:9876
  consume:
     enable: true


